version: '3.8'
services:
  blog_strapi_api:
    container_name: blog_strapi_api
    hostname: blog_strapi_api
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: blog-strapi-1
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - C:/Users/Mate Amargo/Documents/JP/Inttegra/CursoJS/Next/blog-strapi-api:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
